// <auto-generated />
using System;
using BlazorAptit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorAptit.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20211218091805_20211218")]
    partial class _20211218
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BlazorAptit.Models.AptitAnswer", b =>
                {
                    b.Property<int>("AptitAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AQ_1")
                        .HasColumnType("int");

                    b.Property<int>("AQ_10")
                        .HasColumnType("int");

                    b.Property<int>("AQ_11")
                        .HasColumnType("int");

                    b.Property<int>("AQ_12")
                        .HasColumnType("int");

                    b.Property<int>("AQ_13")
                        .HasColumnType("int");

                    b.Property<int>("AQ_14")
                        .HasColumnType("int");

                    b.Property<int>("AQ_15")
                        .HasColumnType("int");

                    b.Property<int>("AQ_16")
                        .HasColumnType("int");

                    b.Property<int>("AQ_17")
                        .HasColumnType("int");

                    b.Property<int>("AQ_18")
                        .HasColumnType("int");

                    b.Property<int>("AQ_19")
                        .HasColumnType("int");

                    b.Property<int>("AQ_2")
                        .HasColumnType("int");

                    b.Property<int>("AQ_20")
                        .HasColumnType("int");

                    b.Property<int>("AQ_3")
                        .HasColumnType("int");

                    b.Property<int>("AQ_4")
                        .HasColumnType("int");

                    b.Property<int>("AQ_5")
                        .HasColumnType("int");

                    b.Property<int>("AQ_6")
                        .HasColumnType("int");

                    b.Property<int>("AQ_7")
                        .HasColumnType("int");

                    b.Property<int>("AQ_8")
                        .HasColumnType("int");

                    b.Property<int>("AQ_9")
                        .HasColumnType("int");

                    b.Property<int>("AptitUserID")
                        .HasColumnType("int");

                    b.Property<int?>("AptitUserID1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("AptitAnswerID");

                    b.HasIndex("AptitUserID");

                    b.HasIndex("AptitUserID1")
                        .IsUnique()
                        .HasFilter("[AptitUserID1] IS NOT NULL");

                    b.ToTable("AptitAnswer");
                });

            modelBuilder.Entity("BlazorAptit.Models.AptitGroup", b =>
                {
                    b.Property<string>("Group_ID")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CheckType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CompletCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Group_City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Group_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manage_Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Manage_Tel1")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Manage_Tel2")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("Payment")
                        .HasColumnType("int");

                    b.Property<string>("PaymentComplet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Group_ID");

                    b.ToTable("AptitGroup");
                });

            modelBuilder.Entity("BlazorAptit.Models.AptitQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("QUE_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUE_9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AptitQuestion");
                });

            modelBuilder.Entity("BlazorAptit.Models.AptitReply", b =>
                {
                    b.Property<int>("AptitReplyID")
                        .HasColumnType("int");

                    b.Property<string>("CONTENT_MAIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART1_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART1_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART2_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART2_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART3_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART3_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART4_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART4_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART5_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART5_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART6_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART6_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART7_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPART7_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB1_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB1_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB2_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB2_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB3_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB3_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB4_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB4_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB5_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB5_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB6_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB6_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB7_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB7_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB8_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB8_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION1_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION1_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION1_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION2_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION2_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION2_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION3_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION3_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION3_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION4_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION4_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION4_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION5_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION5_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION5_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION6_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION6_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION6_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<string>("STUDY_STYLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDY_WAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE_ENG")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AptitReply");
                });

            modelBuilder.Entity("BlazorAptit.Models.AptitResult", b =>
                {
                    b.Property<int>("AptitResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CONTENT_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_1_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_2_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_3_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_4_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_5_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_6_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTENT_MAIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AptitResultID");

                    b.ToTable("AptitResult");
                });

            modelBuilder.Entity("BlazorAptit.Models.AptitUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Group_City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Group_ID")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Group_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("User_Age")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("User_Class")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_Edu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("User_Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("User_Finish")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("User_Grade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_Job")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("User_Password")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("User_Password2")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("agree11")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("Group_ID");

                    b.HasIndex("User_Email")
                        .IsUnique();

                    b.ToTable("AptitUser");
                });

            modelBuilder.Entity("BlazorAptit.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("BlazorAptit.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("BlazorAptit.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("BlazorAptit.Models.AptitAnswer", b =>
                {
                    b.HasOne("BlazorAptit.Models.AptitUser", "AptitUsers")
                        .WithMany("AptitAnswers")
                        .HasForeignKey("AptitUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAptit.Models.AptitUser", null)
                        .WithOne("aptitAnswer")
                        .HasForeignKey("BlazorAptit.Models.AptitAnswer", "AptitUserID1");

                    b.Navigation("AptitUsers");
                });

            modelBuilder.Entity("BlazorAptit.Models.AptitUser", b =>
                {
                    b.HasOne("BlazorAptit.Models.AptitGroup", "Group")
                        .WithMany("AptitUsers")
                        .HasForeignKey("Group_ID");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BlazorAptit.Models.Enrollment", b =>
                {
                    b.HasOne("BlazorAptit.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAptit.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BlazorAptit.Models.AptitGroup", b =>
                {
                    b.Navigation("AptitUsers");
                });

            modelBuilder.Entity("BlazorAptit.Models.AptitUser", b =>
                {
                    b.Navigation("aptitAnswer");

                    b.Navigation("AptitAnswers");
                });

            modelBuilder.Entity("BlazorAptit.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("BlazorAptit.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
